name: Setup Node & PNPM

inputs:
  node-version:
    required: true
    default: 20

  install-dependencies:
    required: true
    default: true

runs:
  using: 'composite'
  steps:
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: pnpm

    - name: Install dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: pnpm install --frozen-lockfile
      shell: bash
