name: Run E2E Tests

inputs:
  preview-url:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install Playwright browsers
      run: pnpm --filter e2e exec playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm --filter e2e exec playwright test

    - name: Generate Playwright report summary (success)
      if: always()
      id: summary
      uses: daun/playwright-report-summary@v3
      with:
        report-url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        report-file: packages/e2e/test-results/results.json

    - name: Upload Playwright report (failure)
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
