name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest
    name: Lint, Typecheck, Test & Build

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run linters
        run: pnpm lint

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run unit tests
        run: pnpm test

      - name: Build application
        run: pnpm build
