name: Continuous Integration

on:
  push:
    branches: ['main']
  pull_request:
    types: [opened, synchronize]

jobs:
  integration:
    runs-on: ubuntu-latest
    name: Lint, Typecheck, Test & Build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.4.0
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linters
        run: pnpm lint

      - name: Run typecheck
        run: pnpm typecheck

      - name: Run unit tests
        run: pnpm test

      - name: Build application
        run: pnpm build
