name: Deploy

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.4.0
        with:
          run_install: false
      - uses: actions/setup-node@v3.8.1
        with:
          node-version: '18'
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm --filter next build
