name: Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    name: Deploy PR Preview
    if: github.event.action != 'closed'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4.0.1
        with:
          node-version: '18'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm --filter next build
        env:
          NEXT_PUBLIC_BASE_PATH: /pr-${{ github.event.number }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to S3
        run: |
          aws s3 sync ./apps/next/out s3://${{ secrets.AWS_S3_BUCKET_NAME }}/pr-${{ github.event.number }} --delete

      - name: Comment PR with preview URL
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.number;
            const bucketName = '${{ secrets.AWS_S3_BUCKET_NAME }}';
            const region = '${{ secrets.AWS_DEFAULT_REGION }}';

            // Construct the S3 website URL (adjust based on your S3 setup)
            const previewUrl = `https://${bucketName}.s3-website-${region}.amazonaws.com/pr-${prNumber}`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **Preview Environment Deployed**\n\n📍 Preview URL: ${previewUrl}\n\n_This preview will be automatically cleaned up when the PR is closed._`
            });

  cleanup-preview:
    runs-on: ubuntu-latest
    name: Cleanup Preview
    if: github.event.action == 'closed'

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Remove preview files
        run: |
          aws s3 rm s3://${{ secrets.AWS_S3_BUCKET_NAME }}/pr-${{ github.event.number }} --recursive

      - name: Comment cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.number;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🧹 **Preview Environment Cleaned Up**\n\nThe preview environment for this PR has been removed.`
            });
