name: Preview Environment

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    name: Deploy Preview Environment

    steps:
      - name: start deployment
        uses: bobheadxi/deployments@f235d02c2daaaa84c710d013c7d39f7f0f8bf298
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: release

      # - name: do my deploy
      #   # ...

      - name: update deployment status
        uses: bobheadxi/deployments@f235d02c2daaaa84c710d013c7d39f7f0f8bf298
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
