name: Production Environment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy-production-environment:
    runs-on: ubuntu-latest
    name: Deploy to Production

    steps:
      - name: Checkout code
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build application
        run: pnpm --filter next build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./apps/next/out s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
