name: Temporary Debug
on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up secret file
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
        run: |
          echo $AWS_ACCESS_KEY_ID >> secrets.txt
          echo $AWS_SECRET_ACCESS_KEY >> secrets.txt
          echo $AWS_DEFAULT_REGION >> secrets.txt
          echo $AWS_S3_BUCKET_NAME >> secrets.txt

      - name: Run tmate
        uses: mxschmitt/action-tmate@v2
