name: Web Performance Audit

on:
  workflow_call:
    inputs:
      preview_url:
        required: true
        type: string

jobs:
  run-web-performance-audit:
    runs-on: ubuntu-latest
    name: Run Web Performance Audit

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Audit preview url using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ inputs.preview_url }}
          uploadArtifacts: false
          temporaryPublicStorage: false
