name: Web Performance Audit

permissions:
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    name: Run Lighthouse Audit

    steps:
      - name: Wait for preview deployment
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.head_ref }}
          check-name: 'Deploy Preview Environment'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: ./.github/actions/setup-node

      - name: Restore cached preview url
        uses: actions/cache/restore@v4
        with:
          path: /tmp/shared
          key: preview-url-${{ github.event.number }}

      - name: Get preview url
        id: get_preview_url
        run: |
          preview_url=$(cat /tmp/shared/preview_url.txt)
          echo "preview-url=$preview_url" >> $GITHUB_OUTPUT

      - name: Run audit
        id: run_audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ steps.get_preview_url.outputs.preview-url }}
          uploadArtifacts: true
          temporaryPublicStorage: true

      - name: Generate Lighthouse performance report
        uses: marocchino/sticky-pull-request-comment@v2.9.4
        with:
          message: |
            ## Lighthouse Performance Report

            [View report](${{ steps.run_audit.outputs.links }})
